// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TimedTodo.Data;

namespace TimedTodo.Data.Migrations
{
    [DbContext(typeof(TimedTodoContext))]
    [Migration("20200917025727_SeedInitialTaskDefinitions")]
    partial class SeedInitialTaskDefinitions
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TimedTodo.Domain.TaskDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TaskDefinitions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("70cb13f8-a0ed-4e3f-b534-957c981d7dfb"),
                            Title = "First Task Definition"
                        },
                        new
                        {
                            Id = new Guid("4e3741cf-7025-4192-8158-c38fc3d53fe5"),
                            Title = "Second Task Definition"
                        },
                        new
                        {
                            Id = new Guid("ace0a6f2-f01c-4217-9ea0-5aa9912bf767"),
                            Title = "Third Task Definition"
                        },
                        new
                        {
                            Id = new Guid("9f75d6a2-4820-476b-b9a4-a7332b899063"),
                            Title = "Forth Task Definition"
                        },
                        new
                        {
                            Id = new Guid("d0e39ceb-2bfe-47c8-ad6d-eb24d79ff11f"),
                            Title = "Fifth Task Definition"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
