// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TimedTodo.Data;

namespace TimedTodo.Data.Migrations
{
    [DbContext(typeof(TimedTodoContext))]
    [Migration("20201027041621_ForeignKeyToTaskInstance")]
    partial class ForeignKeyToTaskInstance
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TimedTodo.Domain.TaskDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("DefaultTimeSpan")
                        .HasColumnType("bigint");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TaskDefinitions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c563fcb5-d15f-4a1d-853f-269c80ae102c"),
                            DefaultTimeSpan = 0L,
                            Title = "TaskDefinition 1"
                        },
                        new
                        {
                            Id = new Guid("9d9c89cb-8a3a-42f1-b88d-bd6230acb1b4"),
                            DefaultTimeSpan = 0L,
                            Title = "TaskDefinition 2"
                        },
                        new
                        {
                            Id = new Guid("8df6cb74-382a-4578-8836-0a0048a2fec5"),
                            DefaultTimeSpan = 0L,
                            Title = "TaskDefinition 3"
                        },
                        new
                        {
                            Id = new Guid("f215df93-3c32-4e1c-8a56-ad5fa98b7a40"),
                            DefaultTimeSpan = 0L,
                            Title = "TaskDefinition 4"
                        },
                        new
                        {
                            Id = new Guid("057c8b15-2028-4abe-b3e1-b01d32a1f978"),
                            DefaultTimeSpan = 0L,
                            Title = "TaskDefinition 5"
                        },
                        new
                        {
                            Id = new Guid("db9a4019-7bc5-4c1a-8aa2-0e055732a3cd"),
                            DefaultTimeSpan = 0L,
                            Title = "TaskDefinition 6"
                        },
                        new
                        {
                            Id = new Guid("126dea40-fe2c-4604-8d3b-a57b58294b26"),
                            DefaultTimeSpan = 0L,
                            Title = "TaskDefinition 7"
                        },
                        new
                        {
                            Id = new Guid("4d9416f7-8f21-4739-9ce5-13a8f0e3ca2b"),
                            DefaultTimeSpan = 0L,
                            Title = "TaskDefinition 8"
                        },
                        new
                        {
                            Id = new Guid("d2e0f165-990e-48af-ae4f-255d624f8309"),
                            DefaultTimeSpan = 0L,
                            Title = "TaskDefinition 9"
                        },
                        new
                        {
                            Id = new Guid("4eefbef3-53cb-4027-8b41-4c6af1567983"),
                            DefaultTimeSpan = 0L,
                            Title = "TaskDefinition 10"
                        });
                });

            modelBuilder.Entity("TimedTodo.Domain.TaskInstance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("ElapsedTime")
                        .HasColumnType("bigint");

                    b.Property<Guid>("TaskDefinitionId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TaskDefinitionId");

                    b.ToTable("TaskInstances");
                });

            modelBuilder.Entity("TimedTodo.Domain.TaskInstance", b =>
                {
                    b.HasOne("TimedTodo.Domain.TaskDefinition", "TaskDefinition")
                        .WithMany()
                        .HasForeignKey("TaskDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
