// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TimedTodo.Data;

namespace TimedTodo.Data.Migrations
{
    [DbContext(typeof(TimedTodoContext))]
    [Migration("20210112044036_TotalTimeAddedToTaskInstance")]
    partial class TotalTimeAddedToTaskInstance
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TimedTodo.Domain.TaskDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("DefaultTimeSpan")
                        .HasColumnType("bigint");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.ToTable("TaskDefinitions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("3fcc981a-e897-4d60-9477-60a554cb743b"),
                            DefaultTimeSpan = 0L,
                            Title = "TaskDefinition 1"
                        },
                        new
                        {
                            Id = new Guid("dc8bc4b9-a10e-4bbe-917c-9a0c7907b6f7"),
                            DefaultTimeSpan = 0L,
                            Title = "TaskDefinition 2"
                        },
                        new
                        {
                            Id = new Guid("f44a024c-9533-4bd5-9e3f-45eee625e72e"),
                            DefaultTimeSpan = 0L,
                            Title = "TaskDefinition 3"
                        },
                        new
                        {
                            Id = new Guid("887617e3-af07-4200-8910-f0c9b5b29f24"),
                            DefaultTimeSpan = 0L,
                            Title = "TaskDefinition 4"
                        },
                        new
                        {
                            Id = new Guid("15153bcf-3d0e-4a9d-a5fa-03ab3eea871d"),
                            DefaultTimeSpan = 0L,
                            Title = "TaskDefinition 5"
                        },
                        new
                        {
                            Id = new Guid("7286d37e-fb48-4163-a01a-783a05e5f241"),
                            DefaultTimeSpan = 0L,
                            Title = "TaskDefinition 6"
                        },
                        new
                        {
                            Id = new Guid("fc372706-fa10-464b-b39a-f65038866eb5"),
                            DefaultTimeSpan = 0L,
                            Title = "TaskDefinition 7"
                        },
                        new
                        {
                            Id = new Guid("6de3c3f0-7d58-4eb7-a83a-0c8f4bb5c361"),
                            DefaultTimeSpan = 0L,
                            Title = "TaskDefinition 8"
                        },
                        new
                        {
                            Id = new Guid("49ef5a9d-385e-47ac-b7f8-1f9824fb6093"),
                            DefaultTimeSpan = 0L,
                            Title = "TaskDefinition 9"
                        },
                        new
                        {
                            Id = new Guid("a4024854-1b36-460c-965f-8460a64fe500"),
                            DefaultTimeSpan = 0L,
                            Title = "TaskDefinition 10"
                        });
                });

            modelBuilder.Entity("TimedTodo.Domain.TaskInstance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("ElapsedTime")
                        .HasColumnType("bigint");

                    b.Property<Guid>("TaskDefinitionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<TimeSpan>("TotalTime")
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.HasIndex("TaskDefinitionId");

                    b.ToTable("TaskInstances");
                });

            modelBuilder.Entity("TimedTodo.Domain.TaskInstance", b =>
                {
                    b.HasOne("TimedTodo.Domain.TaskDefinition", "TaskDefinition")
                        .WithMany("TaskInstances")
                        .HasForeignKey("TaskDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
